ci

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,20 +1,20 @@
 name: Releases
 on:
   push:
-    branches:
-      - 'feature/HU**'
+    branches: [ develop ]
 jobs:
   jobValidacion:
     name: Palabra clave
     runs-on: ubuntu-latest
     steps:
-      - name: Validacion Release
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Ejecutar Release
         if: ${{ !contains(github.event.head_commit.message, 'RELEASE') }}
         run: |
             echo "No se puede hacer release sin la solicitud de RELEASE en el commit"
             exit 1
-        env:
-          RAMA_FEATURE: ${{ github.ref }}
 
   jobPruebas:
     name: Pruebas
@@ -23,15 +23,45 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
+
       - name: Configuración
         uses: actions/setup-python@v2
         with:
           python-version: '3.7'
+
       - name: Instalar dependencias
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
+
       - name: Correr pruebas
         id: correr-pruebas
         run: python -m unittest -v tests/test_logica.py
 
+      - name: Validar resultado con errores
+        if: ${{ failure() }}
+        env:
+          MENSAJE_ERROR: Una o varias pruebas fallaron
+        run: |
+          echo "::set-output name=resultado::$MENSAJE_ERROR"
+          exit 1
+
+  jobRelease:
+    name: Release
+    runs-on: ubuntu-latest
+    needs: jobPruebas
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Crear Rama
+        run: |
+          git checkout -b release
+          git push -f -u origin release
+
+      - name: Mezclar Ramas
+        uses: tukasz/direct-merge-action@master
+        with:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          source-branch: release
+          target-branch: main
